name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C++ environment
        uses: actions/setup-cpp@v1
        with:
          gcc: 11

      - name: Build the program
        run: |
          g++ -o eval2.cpp

      - name: Run tests
        run: |
          ./Eval
